### ISSUE TITLE
"image_representation/ViT_pca_representation.csv"

### ISSUE THREAD

**Issue by zhubbbzhu** [nayu0419/stMMR#4]
Hello, this research is indeed an excellent piece of work. Could you please upload a code regarding the image processing procedure? The provided code involves data such as "image_representation/ViT_pca_representation.csv".But I can't get them. Thank you!

**Comment by nayu0419** [comment]
Hello,

Thank you for your interest in our research and for your kind words.

The file "image_representation/ViT_pca_representation.csv" is available on Zenodo. You can access it through the following link: https://zenodo.org/records/11231758.
